import {
  User,
  Career,
  Skill,
  Assessment,
  Roadmap,
  SkillGapAnalysis,
  Quiz,
  Project,
  CareerReadiness,
} from '../types';

export const mockSkills: Skill[] = [
  { _id: 's1', name: 'HTML', category: 'Frontend', description: 'Semantic markup for modern accessible web pages.', difficulty: 'Beginner', prerequisites: [] },
  { _id: 's2', name: 'CSS', category: 'Frontend', description: 'Modern stylesheets including Flexbox, Grid, and animations.', difficulty: 'Beginner', prerequisites: ['s1'] },
  { _id: 's3', name: 'JavaScript', category: 'Programming', description: 'ES6+ dynamic programming language for interactive web experiences.', difficulty: 'Beginner', prerequisites: ['s1', 's2'] },
  { _id: 's4', name: 'TypeScript', category: 'Programming', description: 'Typed superset of JavaScript enhancing maintainability.', difficulty: 'Intermediate', prerequisites: ['s3'] },
  { _id: 's5', name: 'React', category: 'Frontend', description: 'Declarative component-based UI library with hooks.', difficulty: 'Intermediate', prerequisites: ['s3'] },
  { _id: 's6', name: 'Node.js', category: 'Backend', description: 'Asynchronous event-driven JavaScript server runtime.', difficulty: 'Intermediate', prerequisites: ['s3'] },
  { _id: 's7', name: 'Express', category: 'Backend', description: 'Fast, minimalist web application framework for Node.js.', difficulty: 'Intermediate', prerequisites: ['s6'] },
  { _id: 's8', name: 'MongoDB', category: 'Database', description: 'Document-oriented NoSQL database with flexible JSON-like schemas.', difficulty: 'Intermediate', prerequisites: ['s6'] },
  { _id: 's9', name: 'Git', category: 'DevOps & Tools', description: 'Distributed version control system for tracking source code.', difficulty: 'Beginner', prerequisites: [] },
  { _id: 's10', name: 'REST APIs', category: 'Backend', description: 'Standardized architectural style for networked web services.', difficulty: 'Intermediate', prerequisites: ['s6'] },
];

export const mockCareers: Career[] = [
  {
    _id: '6ac5d095a05b52ab9f9324fe',
    name: 'Full Stack Developer',
    slug: 'full-stack-developer',
    description: 'Engineers who master both frontend clients and backend servers, delivering end-to-end web applications with modern databases and APIs.',
    difficulty: 'Advanced',
    requiredSkills: [
      { skill: mockSkills[0], requiredLevel: 90, importance: 'Essential' },
      { skill: mockSkills[1], requiredLevel: 85, importance: 'Essential' },
      { skill: mockSkills[2], requiredLevel: 90, importance: 'Essential' },
      { skill: mockSkills[3], requiredLevel: 80, importance: 'Important' },
      { skill: mockSkills[4], requiredLevel: 85, importance: 'Essential' },
      { skill: mockSkills[5], requiredLevel: 85, importance: 'Essential' },
      { skill: mockSkills[6], requiredLevel: 80, importance: 'Important' },
      { skill: mockSkills[7], requiredLevel: 80, importance: 'Essential' },
      { skill: mockSkills[8], requiredLevel: 85, importance: 'Essential' },
      { skill: mockSkills[9], requiredLevel: 90, importance: 'Essential' },
    ],
    prerequisites: ['Basic programming', 'Web fundamentals'],
    learningPhases: [
      { phaseNumber: 1, title: 'Web Foundations', description: 'HTML5 semantic tags, CSS modern layouts, and core JavaScript fundamentals.' },
      { phaseNumber: 2, title: 'Frontend Mastery', description: 'React component lifecycles, hooks, styling libraries, and state management.' },
      { phaseNumber: 3, title: 'Backend & Server Logic', description: 'Node.js runtime, Express routing, REST APIs, and middleware pipelines.' },
      { phaseNumber: 4, title: 'Data Persistence & Security', description: 'MongoDB schema design, Mongoose models, JWT authentication, and bcrypt encryption.' },
      { phaseNumber: 5, title: 'Production Capstone', description: 'Containerization, cloud deployment, and system design interviews.' },
    ],
    exampleProjects: [
      { title: 'Full Stack LMS Platform', description: 'Course management platform with student auth and video progress tracking.' },
      { title: 'Real-Time Collaboration Dashboard', description: 'Interactive project workspace with live updates and REST API backend.' },
    ],
    interviewTopics: [
      'Event loop and asynchronous JavaScript execution',
      'React virtual DOM, reconciliation, and hook rules',
      'REST architectural principles vs GraphQL',
      'Database indexing and aggregation pipelines',
      'JWT token security and CORS mitigation',
    ],
  },
  {
    _id: '6ac5d095a05b52ab9f9324ff',
    name: 'Frontend Developer',
    slug: 'frontend-developer',
    description: 'Specializes in creating accessible, responsive, and engaging user interfaces using modern web technologies and client frameworks.',
    difficulty: 'Intermediate',
    requiredSkills: [
      { skill: mockSkills[0], requiredLevel: 95, importance: 'Essential' },
      { skill: mockSkills[1], requiredLevel: 95, importance: 'Essential' },
      { skill: mockSkills[2], requiredLevel: 90, importance: 'Essential' },
      { skill: mockSkills[4], requiredLevel: 90, importance: 'Essential' },
    ],
    prerequisites: ['HTML & CSS basics'],
    learningPhases: [
      { phaseNumber: 1, title: 'Markup & Styling', description: 'Responsive layouts with Flexbox and Grid.' },
      { phaseNumber: 2, title: 'Interactive Web', description: 'DOM manipulation and ES6+ features.' },
      { phaseNumber: 3, title: 'Component Architectures', description: 'React component lifecycles, states, and hooks.' },
    ],
    exampleProjects: [{ title: 'E-commerce Storefront', description: 'Responsive product catalog with cart state management.' }],
    interviewTopics: ['CSS specificity and box model', 'State management patterns in React', 'Performance optimizations and lazy loading'],
  },
  {
    _id: '6ac5d095a05b52ab9f932500',
    name: 'Backend Developer',
    slug: 'backend-developer',
    description: 'Designs reliable database architectures, server logic, and high-performance APIs powering web and mobile applications.',
    difficulty: 'Advanced',
    requiredSkills: [
      { skill: mockSkills[5], requiredLevel: 90, importance: 'Essential' },
      { skill: mockSkills[6], requiredLevel: 85, importance: 'Essential' },
      { skill: mockSkills[7], requiredLevel: 85, importance: 'Essential' },
    ],
    prerequisites: ['Programming logic', 'Basic networking'],
    learningPhases: [
      { phaseNumber: 1, title: 'Server Fundamentals', description: 'Event-driven I/O, streams, and HTTP protocols.' },
      { phaseNumber: 2, title: 'Database Optimization', description: 'Indexing, aggregations, and transactional ACID properties.' },
      { phaseNumber: 3, title: 'API Security & Scalability', description: 'Rate limiting, tokens, and caching layers.' },
    ],
    exampleProjects: [{ title: 'Scalable Microservice API', description: 'Distributed REST API with authentication and caching.' }],
    interviewTopics: ['Database query optimization', 'Concurrency and race conditions', 'Microservices vs Monoliths'],
  },
];

export const mockDemoStudent: User = {
  id: '6ac5d095a05b52ab9f932595',
  _id: '6ac5d095a05b52ab9f932595',
  name: 'Alex Johnson',
  email: 'student@college.edu',
  role: 'student',
  college: 'Apex Engineering College',
  course: 'B.Tech',
  department: 'Information Technology',
  year: '3rd Year',
  careerGoal: mockCareers[0],
  experienceLevel: 'Intermediate',
  interests: ['Web Development', 'Cloud Computing', 'AI Applications'],
  knownSkills: ['HTML', 'CSS', 'JavaScript'],
  bio: 'Aspiring Full Stack Engineer passionate about building scalable web applications and AI-driven solutions.',
  onboardingCompleted: true,
};

export const mockDemoAdmin: User = {
  id: '6ac5d095a05b52ab9f932594',
  _id: '6ac5d095a05b52ab9f932594',
  name: 'System Administrator',
  email: 'admin@competency.ai',
  role: 'admin',
  college: 'Global Institute of Technology',
  course: 'M.Tech',
  department: 'Computer Science & Engineering',
  year: 'Faculty / Admin',
  bio: 'Platform administrator overseeing academic competencies, curricula, and system integrity.',
  onboardingCompleted: true,
};

export const mockAssessment: Assessment = {
  _id: '6ac5d095a05b52ab9f932490',
  title: 'Full Stack Developer Diagnostic Assessment',
  career: mockCareers[0],
  durationMinutes: 25,
  questions: [
    {
      _id: 'q1',
      question: 'Which of the following describes the behavior of JavaScript Promise.all()?',
      options: [
        'It rejects immediately if any single promise rejects',
        'It always resolves regardless of rejections',
        'It runs promises sequentially one by one',
        'It waits for only the first promise to settle',
      ],
      difficulty: 'Intermediate',
      type: 'mcq',
      skill: mockSkills[2],
    },
    {
      _id: 'q2',
      question: 'What is the primary purpose of the useMemo hook in React?',
      options: [
        'To memoize expensive calculations between re-renders',
        'To create persistent mutable references that do not trigger renders',
        'To register side-effects after component mounts',
        'To dispatch actions in Redux store',
      ],
      difficulty: 'Intermediate',
      type: 'mcq',
      skill: mockSkills[4],
    },
    {
      _id: 'q3',
      question: 'In an Express middleware pipeline, what happens if next() is not called and a response is not sent?',
      options: [
        'The client HTTP request hangs and eventually times out',
        'Express automatically calls the next route handler',
        'An unhandled exception crashes the Node process',
        'Express returns a default 200 OK status code',
      ],
      difficulty: 'Intermediate',
      type: 'mcq',
      skill: mockSkills[6],
    },
    {
      _id: 'q4',
      question: 'Which index type in MongoDB optimizes search queries across large textual string fields?',
      options: [
        'Text Index',
        'Geospatial 2dsphere Index',
        'TTL (Time-To-Live) Index',
        'Hashed Index',
      ],
      difficulty: 'Intermediate',
      type: 'mcq',
      skill: mockSkills[7],
    },
  ],
};

export const mockSkillGapAnalysis: SkillGapAnalysis = {
  career: {
    id: mockCareers[0]._id,
    name: mockCareers[0].name,
    difficulty: mockCareers[0].difficulty,
  },
  summary: {
    totalSkills: 10,
    masteredCount: 4,
    averageCompetency: 74,
    readinessEstimate: 76,
    criticalGapsCount: 1,
    aiExecutiveSummary: 'Strong performance in foundational frontend technologies. Recommended to prioritize MongoDB indexing and Express middleware architecture.',
  },
  gaps: [
    {
      skillId: 's1',
      skillName: 'HTML',
      category: 'Frontend',
      currentLevel: 90,
      requiredLevel: 90,
      gap: 0,
      priority: 'Low',
      importance: 'Essential',
      status: 'Mastered',
    },
    {
      skillId: 's2',
      skillName: 'CSS',
      category: 'Frontend',
      currentLevel: 85,
      requiredLevel: 85,
      gap: 0,
      priority: 'Low',
      importance: 'Essential',
      status: 'Mastered',
    },
    {
      skillId: 's3',
      skillName: 'JavaScript',
      category: 'Programming',
      currentLevel: 80,
      requiredLevel: 90,
      gap: 10,
      priority: 'Medium',
      importance: 'Essential',
      status: 'Proficient',
    },
    {
      skillId: 's5',
      skillName: 'React',
      category: 'Frontend',
      currentLevel: 65,
      requiredLevel: 85,
      gap: 20,
      priority: 'High',
      importance: 'Essential',
      status: 'Moderate Gap',
    },
    {
      skillId: 's8',
      skillName: 'MongoDB',
      category: 'Database',
      currentLevel: 40,
      requiredLevel: 80,
      gap: 40,
      priority: 'Critical',
      importance: 'Essential',
      status: 'Critical Gap',
    },
  ],
};

export const mockRoadmap: Roadmap = {
  _id: 'rm_1',
  career: mockCareers[0],
  progress: 55,
  generatedByAI: true,
  aiNotes: 'Customized based on your strong grasp of frontend foundations and need for server-side persistence mastery.',
  phases: [
    {
      phaseNumber: 1,
      name: 'Web Foundations',
      description: 'Master HTML5 semantic elements, responsive CSS flexbox/grid, and modern JavaScript syntax.',
      topics: [
        {
          id: 't1',
          title: 'HTML5 Semantic Layouts',
          description: 'Accessible semantic landmarks and document outlines.',
          difficulty: 'Beginner',
          estimatedTime: '4 hours',
          prerequisites: [],
          resources: [{ title: 'MDN HTML Guide', url: 'https://developer.mozilla.org', type: 'Documentation' }],
          completed: true,
        },
        {
          id: 't2',
          title: 'CSS Grid & Modern Flexbox',
          description: 'Two-dimensional alignment, auto-fit, and responsive layouts.',
          difficulty: 'Beginner',
          estimatedTime: '6 hours',
          prerequisites: ['HTML5'],
          resources: [{ title: 'CSS-Tricks Guide to Flexbox', url: 'https://css-tricks.com', type: 'Article' }],
          completed: true,
        },
        {
          id: 't3',
          title: 'ES6+ Features & Promises',
          description: 'Arrow functions, destructuring, promises, and async/await.',
          difficulty: 'Intermediate',
          estimatedTime: '8 hours',
          prerequisites: ['JavaScript Basics'],
          resources: [{ title: 'JavaScript.info Async', url: 'https://javascript.info', type: 'Course' }],
          completed: true,
        },
      ],
    },
    {
      phaseNumber: 2,
      name: 'Frontend Mastery',
      description: 'React component architecture, custom hooks, and state management.',
      topics: [
        {
          id: 't4',
          title: 'React Hooks (useEffect, useMemo, useCallback)',
          description: 'Component lifecycles, memory caching, and optimized rendering.',
          difficulty: 'Intermediate',
          estimatedTime: '10 hours',
          prerequisites: ['ES6+'],
          resources: [{ title: 'React Official Docs', url: 'https://react.dev', type: 'Documentation' }],
          completed: true,
        },
        {
          id: 't5',
          title: 'Client Routing & Global State',
          description: 'React Router v6 and context-based state synchronization.',
          difficulty: 'Intermediate',
          estimatedTime: '8 hours',
          prerequisites: ['React Hooks'],
          resources: [{ title: 'React Router Guide', url: 'https://reactrouter.com', type: 'Documentation' }],
          completed: false,
        },
      ],
    },
    {
      phaseNumber: 3,
      name: 'Backend & Server Logic',
      description: 'Node.js event loop, Express REST API routing, and middleware pipelines.',
      topics: [
        {
          id: 't6',
          title: 'Express Middleware & Routing',
          description: 'Pipeline chaining, global error handlers, and route modularization.',
          difficulty: 'Intermediate',
          estimatedTime: '8 hours',
          prerequisites: ['Node.js basics'],
          resources: [{ title: 'Express Documentation', url: 'https://expressjs.com', type: 'Documentation' }],
          completed: false,
        },
        {
          id: 't7',
          title: 'JWT Authentication & Security',
          description: 'Stateless session tokens, hashing passwords with bcrypt, and CORS.',
          difficulty: 'Intermediate',
          estimatedTime: '6 hours',
          prerequisites: ['Express'],
          resources: [{ title: 'JWT Handbook', url: 'https://jwt.io', type: 'Article' }],
          completed: false,
        },
      ],
    },
    {
      phaseNumber: 4,
      name: 'Data Persistence & Security',
      description: 'MongoDB schema design, Mongoose models, aggregations, and database optimization.',
      topics: [
        {
          id: 't8',
          title: 'Mongoose ODM & Schemas',
          description: 'Document schema definitions, virtuals, hooks, and validations.',
          difficulty: 'Intermediate',
          estimatedTime: '10 hours',
          prerequisites: ['MongoDB Fundamentals'],
          resources: [{ title: 'Mongoose Docs', url: 'https://mongoosejs.com', type: 'Documentation' }],
          completed: false,
        },
        {
          id: 't9',
          title: 'Aggregation Pipelines & Indexes',
          description: 'Complex group stages, lookup joins, and performance indexing.',
          difficulty: 'Advanced',
          estimatedTime: '12 hours',
          prerequisites: ['Mongoose ODM'],
          resources: [{ title: 'MongoDB University', url: 'https://learn.mongodb.com', type: 'Course' }],
          completed: false,
        },
      ],
    },
  ],
};

export const mockCareerReadiness: CareerReadiness = {
  career: {
    id: mockCareers[0]._id,
    name: mockCareers[0].name,
  },
  overallReadiness: 78,
  stage: 'Interview Ready',
  summaryNote: 'Demonstrates outstanding frontend competency. Target MongoDB and backend pipelines to achieve 90%+ readiness.',
  breakdown: [
    {
      category: 'Diagnostic Assessment',
      weight: 35,
      score: 80,
      weightedValue: 28,
      description: 'Covers core JavaScript, React, Express, and Database queries.',
      status: 'On Track',
    },
    {
      category: 'Topic Quizzes',
      weight: 25,
      score: 85,
      weightedValue: 21.25,
      description: 'Continuous validation across modular quizzes.',
      status: 'Exceeding',
    },
    {
      category: 'Practical Projects',
      weight: 25,
      score: 72,
      weightedValue: 18,
      description: 'Hands-on full-stack development and GitHub commits.',
      status: 'Needs Practice',
    },
    {
      category: 'Interview Preparation',
      weight: 15,
      score: 75,
      weightedValue: 11.25,
      description: 'Mock technical scenarios and architectural verbal responses.',
      status: 'On Track',
    },
  ],
  formulaExplanation: 'Weighted composite readiness = (Assessment * 0.35) + (Quizzes * 0.25) + (Projects * 0.25) + (Interview * 0.15)',
};

export const mockQuizzes: Quiz[] = [
  {
    _id: 'q1',
    title: 'React Fundamentals & Component Lifecycle',
    skill: mockSkills[4],
    difficulty: 'Intermediate',
    questionCount: 1,
    questions: [
      {
        questionIndex: 0,
        question: 'What is the correct syntax to define a functional state variable in React?',
        options: [
          'const [state, setState] = useState(initialValue);',
          'const state = new State(initialValue);',
          'const state = this.state(initialValue);',
          'let state = React.createState(initialValue);',
        ],
      },
    ],
  },
  {
    _id: 'q2',
    title: 'Node.js & Express REST Architecture',
    skill: mockSkills[6],
    difficulty: 'Intermediate',
    questionCount: 1,
    questions: [
      {
        questionIndex: 0,
        question: 'Which HTTP method is specifically intended for partial modifications to an existing resource?',
        options: ['PATCH', 'PUT', 'POST', 'GET'],
      },
    ],
  },
];

export const mockProjects: Project[] = [
  {
    _id: 'p1',
    title: 'Full-Stack E-Commerce Platform with Stripe Checkout',
    description: 'Develop a production-grade online marketplace with catalog browsing, authentication, and secure payment processing.',
    difficulty: 'Advanced',
    technologies: ['React', 'TypeScript', 'Node.js', 'Express', 'MongoDB', 'Tailwind CSS'],
    requirements: [
      'User registration, login, and JWT session handling',
      'Responsive product catalog with search, filter, and pagination',
      'Cart persistence in localStorage and server-side checkout validation',
    ],
    expectedOutcome: 'A deployable multi-page e-commerce app with authenticated user orders and clean REST API structure.',
    skills: [mockSkills[2], mockSkills[4], mockSkills[6], mockSkills[7]],
    submissionStatus: 'Not Started',
  },
  {
    _id: 'p2',
    title: 'Real-Time Team Task & Kanban Board',
    description: 'Build an interactive project collaboration application allowing multi-user drag-and-drop task movements.',
    difficulty: 'Intermediate',
    technologies: ['React', 'TypeScript', 'Tailwind CSS', 'Node.js', 'Express'],
    requirements: [
      'Drag-and-drop column task reordering',
      'Role-based task assignment and priority filtering',
    ],
    expectedOutcome: 'A Kanban board with state persistence, responsive modal editing, and activity tracking.',
    skills: [mockSkills[2], mockSkills[4]],
    submissionStatus: 'Not Started',
  },
];
