import React from 'react';
import { Link } from 'react-router-dom';
import {
  BrainCircuit,
  Target,
  Map,
  Network,
  BookOpen,
  HelpCircle,
  FolderGit2,
  Mic,
  Award,
  ArrowRight,
  ShieldCheck,
  CheckCircle,
} from 'lucide-react';
import { Card } from '../../components/common/Card';
import { Button } from '../../components/common/Button';

export const FeaturesPage: React.FC = () => {
  const featureList = [
    {
      icon: BrainCircuit,
      title: 'AI-Calibrated Skill Assessments',
      desc: 'Industry-calibrated multiple-choice and scenario exams that diagnose practical software abilities beyond rote memorization. Questions dynamically score proficiency across syntax, system design, and edge cases.',
      tags: ['Scenario Questions', 'Automated Scoring', 'No Answer Leaks'],
    },
    {
      icon: Target,
      title: 'Skill Gap & Discrepancy Analysis',
      desc: 'Direct comparison between your current skill levels and the competency benchmarks required for employment. Computes gap percentages and automatically flags Critical, High, and Medium priority areas.',
      tags: ['Severity Tagging', 'Benchmark Metrics', 'Priority Sorting'],
    },
    {
      icon: Map,
      title: 'Personalized AI Learning Roadmaps',
      desc: 'Personalized curriculum mapped across 5 academic phases: Fundamentals, Core Skills, Advanced Topics, Capstones, and Interview Prep, tailored to your college year and demonstrated gaps.',
      tags: ['Gemini AI Generated', 'Topic Checklists', 'State Persistence'],
    },
    {
      icon: Network,
      title: 'Interactive Skill Dependency Tree',
      desc: 'Visual DAG showing prerequisite relationships (e.g. HTML -> CSS -> JavaScript -> React -> Node.js -> MongoDB). Click any node to view required proficiency, resources, and prerequisites.',
      tags: ['Prerequisite DAG', 'Visual Indicators', 'Topic Insights'],
    },
    {
      icon: BookOpen,
      title: 'Curated Academic & Industry Resources',
      desc: 'Verified, high-quality documentation, articles, and courses from official documentation, MDN, and freeCodeCamp. Zero dead links or fake URLs.',
      tags: ['Difficulty Filter', 'Media Categories', 'Search Queries'],
    },
    {
      icon: HelpCircle,
      title: 'Topic Quizzes & Attempt Analytics',
      desc: 'Test your understanding with micro-quizzes. Retain attempt history including latest, average, and peak scores with detailed rationale for every option.',
      tags: ['Instant Feedback', 'Attempt History', 'Detailed Rationale'],
    },
    {
      icon: FolderGit2,
      title: 'Hands-On Portfolio Projects',
      desc: 'College-to-career bridge projects. Submit GitHub repository links and live deployment URLs with validation to verify your hands-on coding proficiency.',
      tags: ['URL Verification', 'Milestone Review', 'Career Portfolio'],
    },
    {
      icon: Mic,
      title: 'AI Mock Interviews & Constructive Feedback',
      desc: 'Simulate technical, HR, and behavioral interview questions. Students type real responses and receive structured, constructive educational feedback generated by AI.',
      tags: ['STAR Method Guidance', 'Weakness Isolation', 'Strengths Summary'],
    },
    {
      icon: Award,
      title: 'Deterministic Career Readiness Index',
      desc: 'A transparent mathematical index weighting assessments (25%), skills (25%), roadmaps (20%), quizzes (10%), projects (10%), and interviews (10%) to measure true job preparedness.',
      tags: ['Transparent Formula', 'Weighted Breakdown', 'Placement Ready'],
    },
  ];

  return (
    <div className="min-h-screen bg-slate-50 py-12">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 space-y-16">
        {/* Header */}
        <div className="text-center max-w-3xl mx-auto space-y-4">
          <span className="px-3.5 py-1.5 rounded-full bg-brand-50 text-brand-700 font-semibold text-xs uppercase tracking-wider border border-brand-200">
            Platform Capabilities
          </span>
          <h1 className="text-4xl sm:text-5xl font-extrabold text-slate-900 tracking-tight">
            Engineered for Real Career Competency
          </h1>
          <p className="text-base sm:text-lg text-slate-600">
            Every feature in SkillPath AI is purpose-built to give college students a clear, actionable path toward engineering excellence.
          </p>
        </div>

        {/* Feature Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {featureList.map((f, i) => {
            const Icon = f.icon;
            return (
              <Card key={i} hover className="p-7 flex flex-col justify-between">
                <div>
                  <div className="w-12 h-12 rounded-2xl bg-brand-50 text-brand-600 flex items-center justify-center mb-5">
                    <Icon className="w-6 h-6" />
                  </div>
                  <h3 className="text-xl font-bold text-slate-900 mb-3">{f.title}</h3>
                  <p className="text-sm text-slate-600 leading-relaxed mb-6">{f.desc}</p>
                </div>
                <div className="pt-4 border-t border-slate-100 flex flex-wrap gap-1.5">
                  {f.tags.map((tag) => (
                    <span key={tag} className="inline-flex items-center gap-1 text-xs px-2.5 py-1 bg-slate-100 text-slate-700 rounded-lg font-medium">
                      <CheckCircle className="w-3 h-3 text-brand-500" />
                      {tag}
                    </span>
                  ))}
                </div>
              </Card>
            );
          })}
        </div>

        {/* CTA */}
        <div className="bg-white rounded-3xl p-8 sm:p-12 border border-slate-200/80 shadow-subtle text-center max-w-4xl mx-auto space-y-6">
          <div className="w-12 h-12 rounded-2xl bg-brand-600 text-white flex items-center justify-center mx-auto">
            <ShieldCheck className="w-6 h-6" />
          </div>
          <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900">
            Start Benchmarking Your Skills Now
          </h2>
          <p className="text-slate-600 max-w-xl mx-auto text-sm sm:text-base">
            Join hundreds of ambitious students bridging the university-to-industry readiness gap.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4 pt-2">
            <Link to="/register">
              <Button size="lg" icon={<ArrowRight className="w-4 h-4 ml-1" />}>
                Create Student Account
              </Button>
            </Link>
            <Link to="/careers">
              <Button variant="outline" size="lg">
                Explore 10 Career Paths
              </Button>
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
};
